### ISSUE TITLE
Comparisons with NFFT.jl

### ISSUE THREAD

**Issue by tknopp** [jipolanco/NonuniformFFTs.jl#24]
Hi,

there are two incorrect statements about the NFFT.jl package:
1. NFFT.jl allows to change the nodes in a plan, see https://juliamath.github.io/NFFT.jl/dev/api/#AbstractNFFTs.nodes!-Union{Tuple{T},%20Tuple{AbstractFTPlan{T},%20Matrix{T}}}%20where%20T
2. It also allows for "performing transforms of multiple quantities at the same non-uniform values at once" see https://juliamath.github.io/NFFT.jl/dev/overview/#Directional

Cheers,

Tobias

**Comment by jipolanco** [comment]
Hi, apologies for these wrong statements and thank you for these corrections. Both statements will be removed.

For some reason I couldn't find the option to change nodes when I tried out NFFT.jl some time ago. As for directional transforms, I guess I had misunderstood this feature when I had read the docs.

Cheers,

Juan

**Comment by tknopp** [comment]
No problem! Thanks for the quick fix. Our documentation certainly is not perfect and the `nodes!` feature was/is pretty hidden.
